import React from "react";
import { Link } from "react-router-dom";

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-green-50 to-green-100 text-gray-800 flex flex-col items-center p-8">
      <div className="max-w-3xl bg-white shadow-lg rounded-2xl p-8 mt-10">
        <h1 className="text-3xl font-bold text-green-700 mb-4 text-center">
          🌍 About Computer Carbon Footprint Analyzer
        </h1>
        <p className="text-lg text-gray-700 mb-6 text-justify">
          The <b>Computer Carbon Footprint Analyzer</b> is a smart web-based platform designed
          to estimate and track the <b>carbon emissions</b> generated by daily computer usage.
          Users can enter details such as device type, power rating, and usage hours to calculate
          their total CO₂ emission. The application promotes <b>eco-conscious computing</b> by
          offering real-time insights and personalized energy-saving suggestions.
        </p>

        <h2 className="text-2xl font-semibold text-green-700 mb-2">🎯 Objectives</h2>
        <ul className="list-disc ml-6 mb-6 text-gray-700">
          <li>To calculate computer-related CO₂ emissions in an accurate and user-friendly way.</li>
          <li>To encourage sustainable digital habits among computer users.</li>
          <li>To visualize environmental impact using graphs and analytics.</li>
          <li>To help individuals and organizations reduce their carbon footprint.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-green-700 mb-2">🧠 Technologies Used</h2>
        <ul className="list-disc ml-6 mb-6 text-gray-700">
          <li><b>Frontend:</b> React.js + Tailwind CSS</li>
          <li><b>Backend:</b> Node.js + Express.js</li>
          <li><b>Database:</b> MongoDB (Mongoose ODM)</li>
          <li><b>Authentication:</b> JWT (JSON Web Token)</li>
          <li><b>Data Visualization:</b> Recharts library</li>
        </ul>

        <h2 className="text-2xl font-semibold text-green-700 mb-2">🌿 Impact</h2>
        <p className="text-lg text-gray-700 mb-6 text-justify">
          By tracking and analyzing computer energy usage, this project helps users understand
          their carbon emissions and take practical steps to reduce them. It contributes to the
          larger goal of <b>sustainable technology and digital responsibility</b>.
        </p>

        <div className="flex justify-center mt-6">
          <Link to="/" className="bg-green-600 text-white px-6 py-2 rounded-lg hover:bg-green-700 transition">
            ⬅ Back to Home
          </Link>
        </div>
      </div>

      <footer className="mt-10 text-sm text-gray-600">
        Developed by <b>Deepak Vishwakarma</b> | Semester 6 Project © 2025
      </footer>
    </div>
  );
}
